//! Shared runtime trait identity for `df-derive`.
//!
//! # What this crate provides
//!
//! `df-derive-core` owns the default `dataframe` traits used by the
//! user-facing `df-derive` facade. Sharing these traits across crates lets
//! derived models compose as nested `ToDataFrame` types without each crate
//! inventing a local runtime identity.
//!
//! The [`dataframe`] module exposes:
//!
//! - [`dataframe::Columnar`] — the checked batch-encoding API supplied for
//!   every hidden `ColumnarSpec` implementation generated by the derive.
//! - [`dataframe::ToDataFrame`] — the per-instance and schema API supplied
//!   uniformly from `Columnar`.
//! - [`dataframe::ToDataFrameVec`] — the slice extension trait that routes
//!   `[T]::to_dataframe()` through `Columnar::encode`.
//! - [`dataframe::Decimal128Encode`] — the contract for encoding a decimal
//!   value as an `i128` mantissa rescaled to a target scale. The reference
//!   `rust_decimal::Decimal` impl is gated behind the `rust_decimal`
//!   feature (enabled by default).
//! - hidden `ColumnarSpec` support for `()` — the zero-column payload behavior
//!   used by generic `Wrapper<()>` shapes. The blanket implementations supply
//!   `Columnar` and `ToDataFrame`.
//!
//! # When to use this crate
//!
//! Most users get this crate through `df-derive`. Depend on this crate
//! directly when you want the shared traits without the facade, or when you
//! use `df-derive-macros` directly and still want the default runtime
//! identity.
//!
//! ```toml
//! [dependencies]
//! df-derive-core = "0.4"
//! df-derive-macros = "0.4"
//! polars = "0.54"
//! ```
//!
//! Default-runtime generated code uses hidden dependency re-exports from this
//! crate, so direct `polars-arrow` dependencies are not required unless you
//! use a custom runtime.
//!
//! ```ignore
//! use df_derive_core::dataframe::{ToDataFrame as _, ToDataFrameVec as _};
//! use df_derive_macros::ToDataFrame;
//!
//! #[derive(ToDataFrame)]
//! struct Trade { symbol: String, price: f64, size: u64 }
//! ```
//!
//! # Validating a custom decimal backend
//!
//! The `Decimal128Encode` contract requires round-half-to-even (banker's
//! rounding) on scale-down. The reference `rust_decimal::Decimal` impl in
//! this crate honours that contract and is checked against Polars' decimal
//! string-cast behavior in this crate's integration tests.

// `polars` pulls a wide transitive dependency tree (ahash, foldhash,
// hashbrown, windows-sys variants, …) where multiple resolved versions are
// unavoidable. `clippy::multiple_crate_versions` is part of the
// `clippy::cargo` group `just lint` enables, and it would fire ~21 times on
// dependencies entirely outside this crate's control. Allow it here so the
// lint surface stays focused on this crate's own code.
#![allow(clippy::multiple_crate_versions)]

pub mod dataframe {
    use std::sync::Arc;

    use polars::prelude::{Column, DataFrame, PolarsResult, Schema, SchemaRef, polars_err};

    #[cfg(feature = "rust_decimal")]
    const DECIMAL128_MAX_SCALE: u32 = 38;

    /// Hidden dependency re-exports used by generated code for the default
    /// dataframe runtime. This is not part of the public API surface.
    #[doc(hidden)]
    pub mod __private {
        pub use polars;
        pub use polars_arrow;
    }

    /// A schema-checked column batch produced by [`Columnar::encode_batch`].
    ///
    /// Its fields are private so only [`ColumnSink`] can construct a batch
    /// after validating schema width, ordered names, data types, and height.
    #[doc(hidden)]
    pub struct EncodedBatch {
        height: usize,
        columns: Vec<Column>,
    }

    impl EncodedBatch {
        /// Consumes the batch and returns its validated columns in schema
        /// order.
        #[doc(hidden)]
        #[must_use]
        pub fn into_columns(self) -> Vec<Column> {
            self.columns
        }

        /// Consumes the batch and constructs its public `DataFrame` boundary.
        #[doc(hidden)]
        #[must_use]
        fn into_dataframe(self) -> DataFrame {
            // SAFETY: `EncodedBatch` has private fields and is constructed
            // only by `ColumnSink::finish`. The sink accepts columns only in
            // the schema's unique name order, and `finish` verifies that
            // every column length equals `height`.
            unsafe { DataFrame::new_unchecked(self.height, self.columns) }
        }
    }

    /// Schema-bound destination used by hidden column encoders.
    ///
    /// The sink checks every column as it is appended. Finalization additionally
    /// checks that no declared column is missing and every column has the row
    /// count observed at the iterator boundary. Construction and finalization
    /// stay private so a `ColumnarSpec` cannot replace its assigned sink with
    /// one bound to a different schema.
    #[doc(hidden)]
    pub struct ColumnSink {
        schema: SchemaRef,
        columns: Vec<Column>,
        producer: &'static str,
    }

    impl ColumnSink {
        /// Creates an empty sink for `schema`.
        #[must_use]
        fn new(schema: SchemaRef, producer: &'static str) -> Self {
            let columns = Vec::with_capacity(schema.len());
            Self {
                schema,
                columns,
                producer,
            }
        }

        /// Appends one column after checking its declared position, name, and
        /// data type.
        ///
        /// # Errors
        ///
        /// Returns an error for an undeclared extra column or a positional
        /// name/data-type mismatch.
        pub fn push(&mut self, column: Column) -> PolarsResult<()> {
            let index = self.columns.len();
            let Some((expected_name, expected_dtype)) = self.schema.get_at_index(index) else {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned column `{}` at index {}, exceeding schema width {}",
                    self.producer,
                    column.name(),
                    index,
                    self.schema.len(),
                ));
            };

            if column.name() != expected_name {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned column `{}` at index {}, expected `{}`",
                    self.producer,
                    column.name(),
                    index,
                    expected_name,
                ));
            }
            if column.dtype() != expected_dtype {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned dtype {:?} for column `{}` at index {}, expected {:?}",
                    self.producer,
                    column.dtype(),
                    column.name(),
                    index,
                    expected_dtype,
                ));
            }

            self.columns.push(column);
            Ok(())
        }

        /// Finalizes the sink against the actual number of yielded rows.
        ///
        /// # Errors
        ///
        /// Returns an error if a declared column is missing or any column has
        /// a height different from `height`.
        fn finish(self, height: usize) -> PolarsResult<EncodedBatch> {
            if self.columns.len() != self.schema.len() {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned schema width {}, expected {}",
                    self.producer,
                    self.columns.len(),
                    self.schema.len(),
                ));
            }

            for (index, column) in self.columns.iter().enumerate() {
                if column.len() != height {
                    return Err(polars_err!(
                        ComputeError:
                        "df-derive: ColumnarSpec for {} returned height {} for column `{}` at index {}, expected {}",
                        self.producer,
                        column.len(),
                        column.name(),
                        index,
                        height,
                    ));
                }
            }

            Ok(EncodedBatch {
                height,
                columns: self.columns,
            })
        }
    }

    struct CountingIterator<I> {
        inner: I,
        yielded: usize,
    }

    impl<I> CountingIterator<I> {
        const fn new(inner: I) -> Self {
            Self { inner, yielded: 0 }
        }
    }

    impl<I> Iterator for CountingIterator<I>
    where
        I: Iterator,
    {
        type Item = I::Item;

        #[inline]
        fn next(&mut self) -> Option<Self::Item> {
            let item = self.inner.next()?;
            self.yielded += 1;
            Some(item)
        }

        #[inline]
        fn size_hint(&self) -> (usize, Option<usize>) {
            self.inner.size_hint()
        }
    }

    /// Low-level schema and column implementation surface populated by the
    /// derive macro.
    ///
    /// Callers should use [`Columnar`]. Its blanket implementation owns the
    /// input iterator, counts yielded rows, and validates this implementation's
    /// output through [`ColumnSink`].
    ///
    /// # Implementor contract
    ///
    /// `build_schema` must be value-independent and stable across calls.
    /// `encode_columns` must always emit exactly that ordered schema. The
    /// checked boundary enforces width, order, names, data types, and actual
    /// row height for each individual batch; it cannot prove that separate
    /// calls to `build_schema` return the same declaration.
    #[doc(hidden)]
    pub trait ColumnarSpec: Sized {
        /// Builds this type's complete ordered schema without encoding rows.
        ///
        /// # Errors
        ///
        /// Returns an error if schema composition fails.
        fn build_schema() -> PolarsResult<SchemaRef>;

        /// Appends this type's encoded columns to `sink`.
        ///
        /// # Errors
        ///
        /// Returns an error if value encoding or sink validation fails.
        fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
        where
            Self: 'a,
            I: Iterator<Item = &'a Self>;
    }

    /// Checked columnar batch API supplied for every [`ColumnarSpec`].
    pub trait Columnar: ColumnarSpec {
        /// Encodes references from one owned iterator into a validated batch.
        ///
        /// The low-level encoder may consume any prefix. After it succeeds,
        /// this boundary drains the iterator once so height always comes from
        /// the actual yielded row count. If low-level encoding fails, the error
        /// is returned immediately without evaluating the iterator's remainder.
        ///
        /// # Errors
        ///
        /// Returns an error if schema construction, value encoding, or batch
        /// validation fails.
        #[doc(hidden)]
        fn encode_batch<'a, R>(rows: R) -> PolarsResult<EncodedBatch>
        where
            Self: 'a,
            R: IntoIterator<Item = &'a Self>,
        {
            let schema = <Self as ColumnarSpec>::build_schema()?;
            let mut sink = ColumnSink::new(schema, std::any::type_name::<Self>());
            let mut rows = CountingIterator::new(rows.into_iter());

            <Self as ColumnarSpec>::encode_columns(&mut rows, &mut sink)?;
            rows.by_ref().for_each(drop);

            sink.finish(rows.yielded)
        }

        /// Encodes references into a public `DataFrame`.
        ///
        /// # Errors
        ///
        /// Returns an error if schema composition, value encoding, or batch
        /// validation fails.
        #[inline]
        fn encode<'a, R>(rows: R) -> PolarsResult<DataFrame>
        where
            Self: 'a,
            R: IntoIterator<Item = &'a Self>,
        {
            Ok(Self::encode_batch(rows)?.into_dataframe())
        }
    }

    impl<T: ColumnarSpec> Columnar for T {}

    /// Per-instance and schema convenience API supplied for every [`Columnar`]
    /// implementation.
    pub trait ToDataFrame: Columnar {
        /// # Errors
        /// Returns an error if schema composition, value encoding, or batch
        /// validation fails.
        #[inline]
        fn to_dataframe(&self) -> PolarsResult<DataFrame> {
            Self::encode(std::slice::from_ref(self))
        }

        /// # Errors
        /// Returns an error if schema construction or checked empty encoding
        /// fails.
        #[inline]
        fn empty_dataframe() -> PolarsResult<DataFrame> {
            Self::encode(&[] as &[Self])
        }

        /// # Errors
        /// Returns an error if explicit schema composition fails.
        #[inline]
        fn schema() -> PolarsResult<SchemaRef> {
            <Self as ColumnarSpec>::build_schema()
        }
    }

    impl<T: Columnar> ToDataFrame for T {}

    /// Extension trait enabling `.to_dataframe()` on slices (and `Vec` via auto-deref).
    pub trait ToDataFrameVec {
        /// # Errors
        /// Returns an error if schema composition, value encoding, or batch
        /// validation fails.
        fn to_dataframe(&self) -> PolarsResult<DataFrame>;
    }

    impl<T> ToDataFrameVec for [T]
    where
        T: Columnar,
    {
        #[inline]
        fn to_dataframe(&self) -> PolarsResult<DataFrame> {
            <T as Columnar>::encode(self)
        }
    }

    // Unit-type support for generic payloads such as `Wrapper<()>`. Direct
    // derived fields of type `()` are rejected by df-derive, but a generic
    // field instantiated as `()` contributes zero columns while the checked
    // iterator boundary preserves the batch height.
    impl ColumnarSpec for () {
        #[inline]
        fn build_schema() -> PolarsResult<SchemaRef> {
            Ok(Arc::new(Schema::default()))
        }

        #[inline]
        fn encode_columns<'a, I>(_rows: &mut I, _sink: &mut ColumnSink) -> PolarsResult<()>
        where
            Self: 'a,
            I: Iterator<Item = &'a Self>,
        {
            Ok(())
        }
    }

    /// Plug-in trait for converting a decimal value into its `i128`
    /// mantissa rescaled to a target scale.
    ///
    /// Implementers MUST use round-half-to-even (banker's rounding) on
    /// scale-down so the bytes the derive emits match polars's own
    /// `str_to_dec128` path. A `None` return surfaces as a polars
    /// `ComputeError` from the generated code.
    ///
    /// The codegen invokes this method through UFCS on the selected trait
    /// path, so inherent methods with the same name cannot bypass this
    /// contract. Custom backends (`bigdecimal::BigDecimal`,
    /// arbitrary-precision types, …) provide their own impls; this crate
    /// ships a `rust_decimal::Decimal` impl below.
    pub trait Decimal128Encode {
        /// Returns the mantissa as `i128` after rescaling `self` to
        /// `target_scale`, or `None` if the conversion would overflow or
        /// otherwise violate the schema. Implementations MUST round
        /// half-to-even on scale-down.
        fn try_to_i128_mantissa(&self, target_scale: u32) -> Option<i128>;
    }

    impl<T> Decimal128Encode for &T
    where
        T: Decimal128Encode + ?Sized,
    {
        #[inline]
        fn try_to_i128_mantissa(&self, target_scale: u32) -> Option<i128> {
            <T as Decimal128Encode>::try_to_i128_mantissa(*self, target_scale)
        }
    }

    /// Reference [`Decimal128Encode`] impl for [`rust_decimal::Decimal`].
    ///
    /// Banker's-rounding contract: round-half-to-even on scale-down,
    /// `checked_mul` overflow-to-`None` on scale-up. This impl is verified
    /// against polars's `str_to_dec128` on a battery of inputs covering
    /// half-tie boundaries (positive and negative), large magnitudes, and
    /// scale-up overflow by this repository's `df-derive-core` integration
    /// tests.
    #[cfg(feature = "rust_decimal")]
    impl Decimal128Encode for rust_decimal::Decimal {
        #[inline]
        fn try_to_i128_mantissa(&self, target_scale: u32) -> Option<i128> {
            // Bounds: `rust_decimal::Decimal::scale()` is capped at 28,
            // polars caps decimal scale at `DECIMAL128_MAX_SCALE`, so the
            // scale-up `diff` is at most 38 and the scale-down `diff` is at
            // most 28.
            // `10i128.pow(diff)` therefore fits in i128 for either direction
            // (max `10^38 < 2^127`).
            if target_scale > DECIMAL128_MAX_SCALE {
                return None;
            }

            let source_scale = self.scale();
            let mantissa: i128 = self.mantissa();
            if source_scale == target_scale {
                return Some(mantissa);
            }
            if source_scale < target_scale {
                let diff = target_scale - source_scale;
                let pow = 10i128.pow(diff);
                return mantissa.checked_mul(pow);
            }
            // Scale-down with round-half-to-even on the unsigned magnitude,
            // then re-apply sign — matches polars's `div_128_pow10`
            // semantics. The `(abs / pow)` quotient cannot exceed `i128::MAX`
            // because `abs <= i128::MAX as u128` and `pow >= 1`, so the
            // `cast_signed` is value-preserving.
            let diff = source_scale - target_scale;
            let pow = 10i128.pow(diff).cast_unsigned();
            let neg = mantissa < 0;
            let abs = mantissa.unsigned_abs();
            let q = (abs / pow).cast_signed();
            let r = abs % pow;
            let half = pow / 2;
            let rounded = match r.cmp(&half) {
                ::std::cmp::Ordering::Greater => q + 1,
                ::std::cmp::Ordering::Less => q,
                ::std::cmp::Ordering::Equal => q + (q & 1),
            };
            Some(if neg { -rounded } else { rounded })
        }
    }

    #[cfg(test)]
    mod checked_runtime_tests {
        use std::cell::Cell;

        use polars::prelude::{DataType, NamedFrom, Series};

        use super::*;

        fn schema(fields: impl IntoIterator<Item = (&'static str, DataType)>) -> SchemaRef {
            Arc::new(
                fields
                    .into_iter()
                    .map(|(name, dtype)| (name.into(), dtype))
                    .collect(),
            )
        }

        fn assert_error_contains<T>(result: PolarsResult<T>, expected: &str) {
            let Err(error) = result else {
                panic!("expected error containing `{expected}`");
            };
            assert!(
                error.to_string().contains(expected),
                "unexpected error: {error}"
            );
        }

        struct Valid(i64);

        impl ColumnarSpec for Valid {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([("value", DataType::Int64)]))
            }

            fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: Iterator<Item = &'a Self>,
            {
                let values: Vec<i64> = rows.map(|row| row.0).collect();
                sink.push(Series::new("value".into(), values).into())
            }
        }

        struct ConsumesOnlyOne(i64);

        impl ColumnarSpec for ConsumesOnlyOne {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([("value", DataType::Int64)]))
            }

            fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: Iterator<Item = &'a Self>,
            {
                let values: Vec<i64> = rows.next().map(|row| row.0).into_iter().collect();
                sink.push(Series::new("value".into(), values).into())
            }
        }

        struct RejectsRows;

        impl ColumnarSpec for RejectsRows {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([]))
            }

            fn encode_columns<'a, I>(_rows: &mut I, _sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: Iterator<Item = &'a Self>,
            {
                Err(polars_err!(ComputeError: "intentional encoder error"))
            }
        }

        struct Borrowed<'a>(&'a str);

        impl ColumnarSpec for Borrowed<'_> {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([("value", DataType::String)]))
            }

            fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: Iterator<Item = &'a Self>,
            {
                let values: Vec<&str> = rows.map(|row| row.0).collect();
                sink.push(Series::new("value".into(), values).into())
            }
        }

        #[test]
        fn checked_batch_preserves_schema_columns_and_actual_height() -> PolarsResult<()> {
            let rows = [Valid(1), Valid(2), Valid(3)];
            let dataframe = Valid::encode_batch(&rows)?.into_dataframe();

            assert_eq!(dataframe.shape(), (3, 1));
            assert_eq!(dataframe.schema().get("value"), Some(&DataType::Int64));
            Ok(())
        }

        #[test]
        fn checked_boundary_drains_successful_partial_consumers_before_validating_height() {
            let rows = [ConsumesOnlyOne(1), ConsumesOnlyOne(2)];
            assert_error_contains(ConsumesOnlyOne::encode_batch(&rows), "returned height 1");
        }

        #[test]
        fn checked_boundary_does_not_drain_after_encoder_error() {
            let yielded = Cell::new(0);
            let rows = [RejectsRows, RejectsRows];
            let inspected = rows.iter().inspect(|_| yielded.set(yielded.get() + 1));

            assert_error_contains(
                RejectsRows::encode_batch(inspected),
                "intentional encoder error",
            );
            assert_eq!(yielded.get(), 0);
        }

        #[test]
        fn sink_rejects_extra_reordered_mistyped_and_missing_columns() -> PolarsResult<()> {
            let expected = schema([("value", DataType::Int64)]);

            let mut reordered = ColumnSink::new(expected.clone(), "Reordered");
            assert_error_contains(
                reordered.push(Series::new("other".into(), [1_i64]).into()),
                "returned column `other`",
            );

            let mut mistyped = ColumnSink::new(expected.clone(), "Mistyped");
            assert_error_contains(
                mistyped.push(Series::new("value".into(), ["wrong"]).into()),
                "returned dtype",
            );

            let mut extra = ColumnSink::new(expected.clone(), "Extra");
            extra.push(Series::new("value".into(), [1_i64]).into())?;
            assert_error_contains(
                extra.push(Series::new("extra".into(), [2_i64]).into()),
                "schema width 1",
            );

            let missing = ColumnSink::new(expected, "Missing");
            assert_error_contains(missing.finish(1), "returned schema width 0");
            Ok(())
        }

        #[test]
        fn borrowed_models_do_not_require_static_lifetimes() -> PolarsResult<()> {
            let owned = [String::from("one"), String::from("two")];
            let rows = [Borrowed(&owned[0]), Borrowed(&owned[1])];
            let dataframe = Borrowed::encode(&rows)?;

            assert_eq!(dataframe.shape(), (2, 1));
            Ok(())
        }

        #[test]
        fn unit_batches_preserve_height_without_columns() -> PolarsResult<()> {
            let rows = [(), (), ()];
            let dataframe = <() as Columnar>::encode_batch(&rows)?.into_dataframe();

            assert_eq!(dataframe.shape(), (3, 0));
            Ok(())
        }
    }
}
