//! Shared runtime trait identity for `df-derive`.
//!
//! # What this crate provides
//!
//! `df-derive-core` owns the default `dataframe` traits used by the
//! user-facing `df-derive` facade. Sharing these traits across crates lets
//! derived models compose as nested `ToDataFrame` types without each crate
//! inventing a local runtime identity.
//!
//! The [`dataframe`] module exposes:
//!
//! - [`dataframe::Columnar`] — the checked batch-encoding API supplied for
//!   every hidden `ColumnarSpec` implementation generated by the derive.
//! - [`dataframe::ToDataFrame`] — the per-instance and schema API supplied
//!   uniformly from `Columnar`.
//! - [`dataframe::ToDataFrameVec`] — the slice extension trait that routes
//!   `[T]::to_dataframe()` through the known-cardinality encoding path.
//! - [`dataframe::Decimal128Encode`] — the contract for encoding a decimal
//!   value as an `i128` mantissa rescaled to a target scale. The reference
//!   `rust_decimal::Decimal` impl is gated behind the `rust_decimal`
//!   feature (enabled by default).
//! - hidden `ColumnarSpec` support for `()` — the zero-column payload behavior
//!   used by generic `Wrapper<()>` shapes. The blanket implementations supply
//!   `Columnar` and `ToDataFrame`.
//!
//! # When to use this crate
//!
//! Most users get this crate through `df-derive`. Depend on this crate
//! directly when you want the shared traits without the facade, or when you
//! use `df-derive-macros` directly and still want the default runtime
//! identity.
//!
//! ```toml
//! [dependencies]
//! df-derive-core = "0.4"
//! df-derive-macros = "0.4"
//! polars = "0.54"
//! ```
//!
//! Default-runtime generated code uses hidden dependency re-exports from this
//! crate, so direct `polars-arrow` dependencies are not required unless you
//! use a custom runtime.
//!
//! ```ignore
//! use df_derive_core::dataframe::{ToDataFrame as _, ToDataFrameVec as _};
//! use df_derive_macros::ToDataFrame;
//!
//! #[derive(ToDataFrame)]
//! struct Trade { symbol: String, price: f64, size: u64 }
//! ```
//!
//! # Validating a custom decimal backend
//!
//! The `Decimal128Encode` contract requires round-half-to-even (banker's
//! rounding) on scale-down. The reference `rust_decimal::Decimal` impl in
//! this crate honours that contract and is checked against Polars' decimal
//! string-cast behavior in this crate's integration tests.

// `polars` pulls a wide transitive dependency tree (ahash, foldhash,
// hashbrown, windows-sys variants, …) where multiple resolved versions are
// unavoidable. `clippy::multiple_crate_versions` is part of the
// `clippy::cargo` group `just lint` enables, and it would fire ~21 times on
// dependencies entirely outside this crate's control. Allow it here so the
// lint surface stays focused on this crate's own code.
#![allow(clippy::multiple_crate_versions)]

pub mod dataframe {
    use std::sync::Arc;

    use polars::prelude::{
        Column, DataFrame, DataType, PlSmallStr, PolarsResult, Schema, SchemaRef, polars_err,
    };

    #[cfg(feature = "rust_decimal")]
    const DECIMAL128_MAX_SCALE: u32 = 38;

    /// Hidden dependency re-exports used by generated code for the default
    /// dataframe runtime. This is not part of the public API surface.
    #[doc(hidden)]
    pub mod __private {
        pub use polars;
        pub use polars_arrow;
    }

    /// A schema-checked column batch produced by [`Columnar::encode_batch`].
    ///
    /// Its fields are private so only [`ColumnSink`] can construct a batch
    /// after validating schema width, ordered names, data types, and height.
    #[doc(hidden)]
    pub struct EncodedBatch {
        height: usize,
        columns: Vec<Column>,
    }

    impl EncodedBatch {
        /// Consumes the batch and returns its validated columns in schema
        /// order.
        #[doc(hidden)]
        #[must_use]
        pub fn into_columns(self) -> Vec<Column> {
            self.columns
        }

        /// Consumes the batch and constructs its public `DataFrame` boundary.
        #[doc(hidden)]
        #[must_use]
        fn into_dataframe(self) -> DataFrame {
            // SAFETY: `EncodedBatch` has private fields and is constructed
            // only by `ColumnSink::finish`. The sink accepts columns only in
            // the schema's unique name order, and `finish` verifies that
            // every column length equals `height`.
            unsafe { DataFrame::new_unchecked(self.height, self.columns) }
        }
    }

    /// Schema-bound destination used by hidden column encoders.
    ///
    /// The sink checks every column as it is appended. Finalization additionally
    /// checks that no declared column is missing and every column has the row
    /// count observed at the iterator boundary. Construction and finalization
    /// stay private so a `ColumnarSpec` cannot replace its assigned sink with
    /// one bound to a different schema.
    #[doc(hidden)]
    pub struct ColumnSink {
        schema: SchemaRef,
        columns: Vec<Column>,
        producer: &'static str,
    }

    /// The next schema position reserved for one output column.
    ///
    /// A slot borrows its sink until it is either committed or dropped. A
    /// failed commit leaves the sink at the same schema position, so an
    /// encoder cannot accidentally skip a declared column.
    #[doc(hidden)]
    #[must_use]
    pub struct ColumnSlot<'a> {
        columns: &'a mut Vec<Column>,
        producer: &'static str,
        index: usize,
        expected_name: &'a PlSmallStr,
        expected_dtype: &'a DataType,
    }

    impl ColumnSlot<'_> {
        /// Returns the schema-authoritative name for this output position.
        #[must_use]
        #[inline]
        pub const fn name(&self) -> &PlSmallStr {
            self.expected_name
        }

        /// Returns the schema-authoritative data type for this output position.
        #[must_use]
        #[inline]
        pub const fn dtype(&self) -> &DataType {
            self.expected_dtype
        }

        /// Commits a column after validating it against this schema position.
        ///
        /// # Errors
        ///
        /// Returns an error for a name or data-type mismatch. The sink is not
        /// advanced when validation fails.
        #[inline]
        pub fn commit(self, column: Column) -> PolarsResult<()> {
            if column.name() != self.expected_name {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned column `{}` at index {}, expected `{}`",
                    self.producer,
                    column.name(),
                    self.index,
                    self.expected_name,
                ));
            }
            if column.dtype() != self.expected_dtype {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned dtype {:?} for column `{}` at index {}, expected {:?}",
                    self.producer,
                    column.dtype(),
                    column.name(),
                    self.index,
                    self.expected_dtype,
                ));
            }

            self.columns.push(column);
            Ok(())
        }
    }

    impl ColumnSink {
        /// Creates an empty sink for `schema`.
        #[must_use]
        fn new(schema: SchemaRef, producer: &'static str) -> Self {
            let columns = Vec::with_capacity(schema.len());
            Self {
                schema,
                columns,
                producer,
            }
        }

        /// Reserves the next declared output position.
        ///
        /// # Errors
        ///
        /// Returns an error when every declared schema position already has a
        /// committed column.
        #[inline]
        pub fn next_slot(&mut self) -> PolarsResult<ColumnSlot<'_>> {
            let Self {
                schema,
                columns,
                producer,
            } = self;
            let producer = *producer;
            let index = columns.len();
            let Some((expected_name, expected_dtype)) = schema.get_at_index(index) else {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} requested column slot at index {}, exceeding schema width {}",
                    producer,
                    index,
                    schema.len(),
                ));
            };
            Ok(ColumnSlot {
                columns,
                producer,
                index,
                expected_name,
                expected_dtype,
            })
        }

        /// Finalizes the sink against the actual number of yielded rows.
        ///
        /// # Errors
        ///
        /// Returns an error if a declared column is missing or any column has
        /// a height different from `height`.
        fn finish(self, height: usize) -> PolarsResult<EncodedBatch> {
            if self.columns.len() != self.schema.len() {
                return Err(polars_err!(
                    ComputeError:
                    "df-derive: ColumnarSpec for {} returned schema width {}, expected {}",
                    self.producer,
                    self.columns.len(),
                    self.schema.len(),
                ));
            }

            for (index, column) in self.columns.iter().enumerate() {
                if column.len() != height {
                    return Err(polars_err!(
                        ComputeError:
                        "df-derive: ColumnarSpec for {} returned height {} for column `{}` at index {}, expected {}",
                        self.producer,
                        column.len(),
                        column.name(),
                        index,
                        height,
                    ));
                }
            }

            Ok(EncodedBatch {
                height,
                columns: self.columns,
            })
        }
    }

    /// Iterator boundary understood by generated encoders that may need to
    /// revisit already yielded row references.
    ///
    /// General iterators that need replay use a dedicated cursor that captures
    /// references as it advances. Slice-backed cursors can replay their yielded
    /// prefix directly without allocating a second reference buffer.
    ///
    /// # Safety
    ///
    /// `yielded` must report the exact number of items successfully returned by
    /// `Iterator::next`. After `enable_replay` returns successfully, `replay`
    /// must yield exactly those successful source items once each and in source
    /// order. Generated encoders rely on this contract to uphold exact-capacity
    /// unsafe writes.
    #[doc(hidden)]
    pub unsafe trait RowCursor: Iterator {
        /// A fresh iterator over the rows yielded so far, in source order.
        type Replay<'cursor>: Iterator<Item = Self::Item>
        where
            Self: 'cursor;

        /// Enables replay before the first source row is requested.
        ///
        /// `capacity` is the lower bound already observed by generated code;
        /// implementations must not query `size_hint` again.
        fn enable_replay(&mut self, capacity: usize);

        /// Returns a fresh iterator over the rows yielded since replay was
        /// enabled.
        fn replay(&self) -> Self::Replay<'_>;

        /// Returns the number of rows yielded from the source cursor.
        fn yielded(&self) -> usize;
    }

    struct StreamingCursor<I>
    where
        I: Iterator,
    {
        inner: I,
        yielded: usize,
    }

    impl<I> StreamingCursor<I>
    where
        I: Iterator,
    {
        #[inline]
        const fn new(inner: I) -> Self {
            Self { inner, yielded: 0 }
        }
    }

    impl<I> Iterator for StreamingCursor<I>
    where
        I: Iterator,
        I::Item: Copy,
    {
        type Item = I::Item;

        #[inline]
        fn next(&mut self) -> Option<Self::Item> {
            let item = self.inner.next()?;
            self.yielded += 1;
            Some(item)
        }

        #[inline]
        fn size_hint(&self) -> (usize, Option<usize>) {
            self.inner.size_hint()
        }
    }

    unsafe impl<I> RowCursor for StreamingCursor<I>
    where
        I: Iterator,
        I::Item: Copy,
    {
        type Replay<'cursor>
            = std::iter::Empty<I::Item>
        where
            Self: 'cursor;

        #[cold]
        #[inline(never)]
        fn enable_replay(&mut self, _capacity: usize) {
            panic!("df-derive: compact streaming cursor does not support row replay");
        }

        #[inline]
        fn replay(&self) -> Self::Replay<'_> {
            std::iter::empty()
        }

        #[inline]
        fn yielded(&self) -> usize {
            self.yielded
        }
    }

    struct ReplayStreamingCursor<I>
    where
        I: Iterator,
    {
        inner: I,
        yielded: usize,
        replay: Option<Vec<I::Item>>,
    }

    impl<I> ReplayStreamingCursor<I>
    where
        I: Iterator,
    {
        #[inline]
        const fn new(inner: I) -> Self {
            Self {
                inner,
                yielded: 0,
                replay: None,
            }
        }
    }

    impl<I> Iterator for ReplayStreamingCursor<I>
    where
        I: Iterator,
        I::Item: Copy,
    {
        type Item = I::Item;

        #[inline]
        fn next(&mut self) -> Option<Self::Item> {
            let item = self.inner.next()?;
            match &mut self.replay {
                Some(replay) => replay.push(item),
                None => self.yielded += 1,
            }
            Some(item)
        }

        #[inline]
        fn size_hint(&self) -> (usize, Option<usize>) {
            self.inner.size_hint()
        }
    }

    unsafe impl<I> RowCursor for ReplayStreamingCursor<I>
    where
        I: Iterator,
        I::Item: Copy,
    {
        type Replay<'cursor>
            = std::iter::Copied<std::slice::Iter<'cursor, I::Item>>
        where
            Self: 'cursor;

        #[inline]
        fn enable_replay(&mut self, capacity: usize) {
            assert!(
                self.yielded == 0 && self.replay.is_none(),
                "df-derive: row replay must be enabled before iteration",
            );
            self.replay = Some(Vec::with_capacity(capacity));
        }

        #[inline]
        fn replay(&self) -> Self::Replay<'_> {
            self.replay
                .as_ref()
                .expect("df-derive: row replay requested before it was enabled")
                .iter()
                .copied()
        }

        #[inline]
        fn yielded(&self) -> usize {
            self.replay.as_ref().map_or(self.yielded, Vec::len)
        }
    }

    struct SliceCursor<'row, T> {
        original: &'row [T],
        remaining: std::slice::Iter<'row, T>,
    }

    impl<'row, T> SliceCursor<'row, T> {
        #[inline]
        fn new(rows: &'row [T]) -> Self {
            Self {
                original: rows,
                remaining: rows.iter(),
            }
        }
    }

    impl<'row, T> Iterator for SliceCursor<'row, T> {
        type Item = &'row T;

        #[inline]
        fn next(&mut self) -> Option<Self::Item> {
            self.remaining.next()
        }

        #[inline]
        fn size_hint(&self) -> (usize, Option<usize>) {
            self.remaining.size_hint()
        }
    }

    unsafe impl<'row, T> RowCursor for SliceCursor<'row, T> {
        type Replay<'cursor>
            = std::slice::Iter<'row, T>
        where
            Self: 'cursor;

        #[inline]
        fn enable_replay(&mut self, _capacity: usize) {}

        #[inline]
        fn replay(&self) -> Self::Replay<'_> {
            let original: &'row [T] = self.original;
            original[..self.yielded()].iter()
        }

        #[inline]
        fn yielded(&self) -> usize {
            self.original.len() - self.remaining.len()
        }
    }

    struct RefSliceCursor<'slice, 'row, T> {
        original: &'slice [&'row T],
        remaining: std::iter::Copied<std::slice::Iter<'slice, &'row T>>,
    }

    impl<'slice, 'row, T> RefSliceCursor<'slice, 'row, T> {
        #[inline]
        fn new(rows: &'slice [&'row T]) -> Self {
            Self {
                original: rows,
                remaining: rows.iter().copied(),
            }
        }
    }

    impl<'row, T> Iterator for RefSliceCursor<'_, 'row, T> {
        type Item = &'row T;

        #[inline]
        fn next(&mut self) -> Option<Self::Item> {
            self.remaining.next()
        }

        #[inline]
        fn size_hint(&self) -> (usize, Option<usize>) {
            self.remaining.size_hint()
        }
    }

    unsafe impl<'slice, 'row, T> RowCursor for RefSliceCursor<'slice, 'row, T> {
        type Replay<'cursor>
            = std::iter::Copied<std::slice::Iter<'slice, &'row T>>
        where
            Self: 'cursor;

        #[inline]
        fn enable_replay(&mut self, _capacity: usize) {}

        #[inline]
        fn replay(&self) -> Self::Replay<'_> {
            let original: &'slice [&'row T] = self.original;
            original[..self.yielded()].iter().copied()
        }

        #[inline]
        fn yielded(&self) -> usize {
            self.original.len() - self.remaining.len()
        }
    }

    /// Low-level schema and column implementation surface populated by the
    /// derive macro.
    ///
    /// Callers should use [`Columnar::encode`] for iterator inputs or
    /// [`ToDataFrameVec::to_dataframe`] for slices. The checked boundaries
    /// determine actual height by counting yielded iterator rows or using the
    /// slice cardinality, then validate this implementation's output through
    /// [`ColumnSink`].
    ///
    /// # Implementor contract
    ///
    /// `build_schema` must be value-independent and stable across calls.
    /// `encode_columns` must always emit exactly that ordered schema. The
    /// `encode_columns` must acquire each schema position through
    /// [`ColumnSink::next_slot`] and commit it through [`ColumnSlot::commit`].
    /// The checked boundary enforces width, order, names, data types, and
    /// actual row height for each individual batch; it cannot prove that separate
    /// calls to `build_schema` return the same declaration.
    #[doc(hidden)]
    pub trait ColumnarSpec: Sized {
        /// Whether general iterator inputs require buffered row replay.
        #[doc(hidden)]
        const REQUIRES_ROW_REPLAY: bool = false;

        /// Builds this type's complete ordered schema without encoding rows.
        ///
        /// # Errors
        ///
        /// Returns an error if schema composition fails.
        fn build_schema() -> PolarsResult<SchemaRef>;

        /// Appends this type's encoded columns to `sink`.
        ///
        /// # Errors
        ///
        /// Returns an error if value encoding or sink validation fails.
        fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
        where
            Self: 'a,
            I: RowCursor<Item = &'a Self>;
    }

    #[allow(
        clippy::inline_always,
        reason = "the cursor type must specialize away before entering generated row loops"
    )]
    #[inline(always)]
    fn encode_streaming_cursor<'row, T, C>(
        mut rows: C,
        sink: &mut ColumnSink,
    ) -> PolarsResult<usize>
    where
        T: ColumnarSpec + 'row,
        C: RowCursor<Item = &'row T>,
    {
        T::encode_columns(&mut rows, sink)?;
        rows.by_ref().for_each(drop);
        Ok(rows.yielded())
    }

    /// Checked columnar batch API supplied for every [`ColumnarSpec`].
    pub trait Columnar: ColumnarSpec {
        /// Encodes references from one owned iterator into a validated batch.
        ///
        /// The low-level encoder may consume any prefix. After it succeeds,
        /// this boundary drains the iterator once so height always comes from
        /// the actual yielded row count. If low-level encoding fails, the error
        /// is returned immediately without evaluating the iterator's remainder.
        ///
        /// # Errors
        ///
        /// Returns an error if schema construction, value encoding, or batch
        /// validation fails.
        #[doc(hidden)]
        fn encode_batch<'a, R>(rows: R) -> PolarsResult<EncodedBatch>
        where
            Self: 'a,
            R: IntoIterator<Item = &'a Self>,
        {
            let schema = <Self as ColumnarSpec>::build_schema()?;
            let mut sink = ColumnSink::new(schema, std::any::type_name::<Self>());
            let rows = rows.into_iter();
            let height = if <Self as ColumnarSpec>::REQUIRES_ROW_REPLAY {
                encode_streaming_cursor::<Self, _>(ReplayStreamingCursor::new(rows), &mut sink)?
            } else {
                encode_streaming_cursor::<Self, _>(StreamingCursor::new(rows), &mut sink)?
            };

            sink.finish(height)
        }

        /// Encodes a slice without counting rows that already have a known
        /// cardinality.
        ///
        /// # Errors
        ///
        /// Returns an error if schema construction, value encoding, or batch
        /// validation fails.
        #[doc(hidden)]
        fn encode_slice(rows: &[Self]) -> PolarsResult<EncodedBatch> {
            let schema = <Self as ColumnarSpec>::build_schema()?;
            let mut sink = ColumnSink::new(schema, std::any::type_name::<Self>());
            let mut row_iter = SliceCursor::new(rows);

            <Self as ColumnarSpec>::encode_columns(&mut row_iter, &mut sink)?;

            sink.finish(rows.len())
        }

        /// Encodes a slice of row references without allocating another
        /// reference buffer when generated child encoders need replay.
        ///
        /// # Errors
        ///
        /// Returns an error if schema construction, value encoding, or batch
        /// validation fails.
        #[doc(hidden)]
        fn encode_ref_batch<'row>(rows: &[&'row Self]) -> PolarsResult<EncodedBatch>
        where
            Self: 'row,
        {
            let schema = <Self as ColumnarSpec>::build_schema()?;
            let mut sink = ColumnSink::new(schema, std::any::type_name::<Self>());
            let mut row_iter = RefSliceCursor::new(rows);

            <Self as ColumnarSpec>::encode_columns(&mut row_iter, &mut sink)?;
            row_iter.by_ref().for_each(drop);

            sink.finish(rows.len())
        }

        /// Encodes references from a general iterator into a public
        /// `DataFrame`, counting the rows actually yielded.
        ///
        /// For a slice or `Vec<Self>`, prefer [`ToDataFrameVec::to_dataframe`]
        /// so the known row count can be used directly.
        ///
        /// # Errors
        ///
        /// Returns an error if schema composition, value encoding, or batch
        /// validation fails.
        #[inline]
        fn encode<'a, R>(rows: R) -> PolarsResult<DataFrame>
        where
            Self: 'a,
            R: IntoIterator<Item = &'a Self>,
        {
            Ok(Self::encode_batch(rows)?.into_dataframe())
        }
    }

    impl<T: ColumnarSpec> Columnar for T {}

    /// Per-instance and schema convenience API supplied for every [`Columnar`]
    /// implementation.
    pub trait ToDataFrame: Columnar {
        /// # Errors
        /// Returns an error if schema composition, value encoding, or batch
        /// validation fails.
        #[inline]
        fn to_dataframe(&self) -> PolarsResult<DataFrame> {
            Ok(Self::encode_slice(std::slice::from_ref(self))?.into_dataframe())
        }

        /// # Errors
        /// Returns an error if schema construction or checked empty encoding
        /// fails.
        #[inline]
        fn empty_dataframe() -> PolarsResult<DataFrame> {
            Ok(Self::encode_slice(&[])?.into_dataframe())
        }

        /// # Errors
        /// Returns an error if explicit schema composition fails.
        #[inline]
        fn schema() -> PolarsResult<SchemaRef> {
            <Self as ColumnarSpec>::build_schema()
        }
    }

    impl<T: Columnar> ToDataFrame for T {}

    /// Extension trait enabling known-cardinality `.to_dataframe()` conversion
    /// on slices (and `Vec` via auto-deref).
    pub trait ToDataFrameVec {
        /// # Errors
        /// Returns an error if schema composition, value encoding, or batch
        /// validation fails.
        fn to_dataframe(&self) -> PolarsResult<DataFrame>;
    }

    impl<T> ToDataFrameVec for [T]
    where
        T: Columnar,
    {
        #[inline]
        fn to_dataframe(&self) -> PolarsResult<DataFrame> {
            Ok(<T as Columnar>::encode_slice(self)?.into_dataframe())
        }
    }

    // Unit-type support for generic payloads such as `Wrapper<()>`. Direct
    // derived fields of type `()` are rejected by df-derive, but a generic
    // field instantiated as `()` contributes zero columns while the checked
    // iterator boundary preserves the batch height.
    impl ColumnarSpec for () {
        #[inline]
        fn build_schema() -> PolarsResult<SchemaRef> {
            Ok(Arc::new(Schema::default()))
        }

        #[inline]
        fn encode_columns<'a, I>(_rows: &mut I, _sink: &mut ColumnSink) -> PolarsResult<()>
        where
            Self: 'a,
            I: RowCursor<Item = &'a Self>,
        {
            Ok(())
        }
    }

    /// Plug-in trait for converting a decimal value into its `i128`
    /// mantissa rescaled to a target scale.
    ///
    /// Implementers MUST use round-half-to-even (banker's rounding) on
    /// scale-down so the bytes the derive emits match polars's own
    /// `str_to_dec128` path. A `None` return surfaces as a polars
    /// `ComputeError` from the generated code.
    ///
    /// The codegen invokes this method through UFCS on the selected trait
    /// path, so inherent methods with the same name cannot bypass this
    /// contract. Custom backends (`bigdecimal::BigDecimal`,
    /// arbitrary-precision types, …) provide their own impls; this crate
    /// ships a `rust_decimal::Decimal` impl below.
    pub trait Decimal128Encode {
        /// Returns the mantissa as `i128` after rescaling `self` to
        /// `target_scale`, or `None` if the conversion would overflow or
        /// otherwise violate the schema. Implementations MUST round
        /// half-to-even on scale-down.
        fn try_to_i128_mantissa(&self, target_scale: u32) -> Option<i128>;
    }

    impl<T> Decimal128Encode for &T
    where
        T: Decimal128Encode + ?Sized,
    {
        #[inline]
        fn try_to_i128_mantissa(&self, target_scale: u32) -> Option<i128> {
            <T as Decimal128Encode>::try_to_i128_mantissa(*self, target_scale)
        }
    }

    /// Reference [`Decimal128Encode`] impl for [`rust_decimal::Decimal`].
    ///
    /// Banker's-rounding contract: round-half-to-even on scale-down,
    /// `checked_mul` overflow-to-`None` on scale-up. This impl is verified
    /// against polars's `str_to_dec128` on a battery of inputs covering
    /// half-tie boundaries (positive and negative), large magnitudes, and
    /// scale-up overflow by this repository's `df-derive-core` integration
    /// tests.
    #[cfg(feature = "rust_decimal")]
    impl Decimal128Encode for rust_decimal::Decimal {
        #[inline]
        fn try_to_i128_mantissa(&self, target_scale: u32) -> Option<i128> {
            // Bounds: `rust_decimal::Decimal::scale()` is capped at 28,
            // polars caps decimal scale at `DECIMAL128_MAX_SCALE`, so the
            // scale-up `diff` is at most 38 and the scale-down `diff` is at
            // most 28.
            // `10i128.pow(diff)` therefore fits in i128 for either direction
            // (max `10^38 < 2^127`).
            if target_scale > DECIMAL128_MAX_SCALE {
                return None;
            }

            let source_scale = self.scale();
            let mantissa: i128 = self.mantissa();
            if source_scale == target_scale {
                return Some(mantissa);
            }
            if source_scale < target_scale {
                let diff = target_scale - source_scale;
                let pow = 10i128.pow(diff);
                return mantissa.checked_mul(pow);
            }
            // Scale-down with round-half-to-even on the unsigned magnitude,
            // then re-apply sign — matches polars's `div_128_pow10`
            // semantics. The `(abs / pow)` quotient cannot exceed `i128::MAX`
            // because `abs <= i128::MAX as u128` and `pow >= 1`, so the
            // `cast_signed` is value-preserving.
            let diff = source_scale - target_scale;
            let pow = 10i128.pow(diff).cast_unsigned();
            let neg = mantissa < 0;
            let abs = mantissa.unsigned_abs();
            let q = (abs / pow).cast_signed();
            let r = abs % pow;
            let half = pow / 2;
            let rounded = match r.cmp(&half) {
                ::std::cmp::Ordering::Greater => q + 1,
                ::std::cmp::Ordering::Less => q,
                ::std::cmp::Ordering::Equal => q + (q & 1),
            };
            Some(if neg { -rounded } else { rounded })
        }
    }

    #[cfg(test)]
    mod checked_runtime_tests {
        use std::cell::Cell;

        use polars::prelude::{DataType, NamedFrom, Series};

        use super::*;

        fn schema(fields: impl IntoIterator<Item = (&'static str, DataType)>) -> SchemaRef {
            Arc::new(
                fields
                    .into_iter()
                    .map(|(name, dtype)| (name.into(), dtype))
                    .collect(),
            )
        }

        fn assert_error_contains<T>(result: PolarsResult<T>, expected: &str) {
            let Err(error) = result else {
                panic!("expected error containing `{expected}`");
            };
            assert!(
                error.to_string().contains(expected),
                "unexpected error: {error}"
            );
        }

        struct ObservableSizeHint<'rows, 'observer, T> {
            inner: std::slice::Iter<'rows, T>,
            calls: &'observer Cell<usize>,
        }

        impl<'rows, T> Iterator for ObservableSizeHint<'rows, '_, T> {
            type Item = &'rows T;

            fn next(&mut self) -> Option<Self::Item> {
                self.inner.next()
            }

            fn size_hint(&self) -> (usize, Option<usize>) {
                self.calls.set(self.calls.get() + 1);
                self.inner.size_hint()
            }
        }

        struct Valid(i64);

        impl ColumnarSpec for Valid {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([("value", DataType::Int64)]))
            }

            fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: RowCursor<Item = &'a Self>,
            {
                let values: Vec<i64> = rows.map(|row| row.0).collect();
                let slot = sink.next_slot()?;
                let column = Series::new(slot.name().clone(), values);
                slot.commit(column.into())
            }
        }

        struct ConsumesOnlyOne(i64);

        impl ColumnarSpec for ConsumesOnlyOne {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([("value", DataType::Int64)]))
            }

            fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: RowCursor<Item = &'a Self>,
            {
                let values: Vec<i64> = rows.next().map(|row| row.0).into_iter().collect();
                let slot = sink.next_slot()?;
                let column = Series::new(slot.name().clone(), values);
                slot.commit(column.into())
            }
        }

        struct RejectsRows;

        impl ColumnarSpec for RejectsRows {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([]))
            }

            fn encode_columns<'a, I>(_rows: &mut I, _sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: RowCursor<Item = &'a Self>,
            {
                Err(polars_err!(ComputeError: "intentional encoder error"))
            }
        }

        struct Borrowed<'a>(&'a str);

        impl ColumnarSpec for Borrowed<'_> {
            fn build_schema() -> PolarsResult<SchemaRef> {
                Ok(schema([("value", DataType::String)]))
            }

            fn encode_columns<'a, I>(rows: &mut I, sink: &mut ColumnSink) -> PolarsResult<()>
            where
                Self: 'a,
                I: RowCursor<Item = &'a Self>,
            {
                let values: Vec<&str> = rows.map(|row| row.0).collect();
                let slot = sink.next_slot()?;
                let column = Series::new(slot.name().clone(), values);
                slot.commit(column.into())
            }
        }

        #[test]
        fn checked_batch_preserves_schema_columns_and_actual_height() -> PolarsResult<()> {
            let rows = [Valid(1), Valid(2), Valid(3)];
            let dataframe = Valid::encode_batch(&rows)?.into_dataframe();

            assert_eq!(dataframe.shape(), (3, 1));
            assert_eq!(dataframe.schema().get("value"), Some(&DataType::Int64));
            Ok(())
        }

        #[test]
        fn checked_boundary_drains_successful_partial_consumers_before_validating_height() {
            let rows = [ConsumesOnlyOne(1), ConsumesOnlyOne(2)];
            assert_error_contains(ConsumesOnlyOne::encode_batch(&rows), "returned height 1");

            let refs = [&rows[0], &rows[1]];
            assert_error_contains(
                ConsumesOnlyOne::encode_ref_batch(&refs),
                "returned height 1",
            );
        }

        #[test]
        fn checked_boundary_does_not_drain_after_encoder_error() {
            let yielded = Cell::new(0);
            let rows = [RejectsRows, RejectsRows];
            let inspected = rows.iter().inspect(|_| yielded.set(yielded.get() + 1));

            assert_error_contains(
                RejectsRows::encode_batch(inspected),
                "intentional encoder error",
            );
            assert_eq!(yielded.get(), 0);
        }

        #[test]
        fn slice_cursor_replays_the_yielded_prefix_without_buffering() {
            let rows = [10_i32, 20, 30];
            let mut cursor = SliceCursor::new(&rows);
            cursor.enable_replay(rows.len());

            assert_eq!(cursor.next(), Some(&10));
            assert_eq!(cursor.next(), Some(&20));
            assert_eq!(cursor.yielded(), 2);

            let replay: std::slice::Iter<'_, i32> = cursor.replay();
            assert_eq!(replay.copied().collect::<Vec<_>>(), [10, 20]);
        }

        #[test]
        fn reference_slice_cursor_replays_original_row_references() {
            let rows = [10_i32, 20, 30];
            let refs = [&rows[0], &rows[1], &rows[2]];
            let mut cursor = RefSliceCursor::new(&refs);
            cursor.enable_replay(refs.len());

            assert_eq!(cursor.next(), Some(&10));
            assert_eq!(cursor.next(), Some(&20));
            assert_eq!(cursor.yielded(), 2);

            let replay: std::iter::Copied<std::slice::Iter<'_, &'_ i32>> = cursor.replay();
            assert_eq!(replay.copied().collect::<Vec<_>>(), [10, 20]);
        }

        #[test]
        fn streaming_cursor_observes_size_hint_once_and_counts_yielded_rows() {
            let rows = [10_i32, 20, 30];
            let size_hint_calls = Cell::new(0);
            let source = ObservableSizeHint {
                inner: rows.iter(),
                calls: &size_hint_calls,
            };
            let mut cursor = StreamingCursor::new(source);

            let (capacity, upper_bound) = cursor.size_hint();
            assert_eq!((capacity, upper_bound), (rows.len(), Some(rows.len())));
            cursor.by_ref().for_each(drop);

            assert_eq!(size_hint_calls.get(), 1);
            assert_eq!(cursor.yielded(), rows.len());
            let replay: std::iter::Empty<&i32> = cursor.replay();
            assert_eq!(replay.count(), 0);
        }

        #[test]
        fn replay_streaming_cursor_observes_size_hint_once_and_replays_yielded_rows() {
            let rows = [10_i32, 20, 30];
            let size_hint_calls = Cell::new(0);
            let source = ObservableSizeHint {
                inner: rows.iter(),
                calls: &size_hint_calls,
            };
            let mut cursor = ReplayStreamingCursor::new(source);

            let (capacity, upper_bound) = cursor.size_hint();
            assert_eq!((capacity, upper_bound), (rows.len(), Some(rows.len())));
            cursor.enable_replay(capacity);
            cursor.by_ref().for_each(drop);

            assert_eq!(size_hint_calls.get(), 1);
            assert_eq!(cursor.yielded(), rows.len());
            let replay: std::iter::Copied<std::slice::Iter<'_, &'_ i32>> = cursor.replay();
            assert_eq!(replay.copied().collect::<Vec<_>>(), rows);
        }

        #[test]
        #[should_panic(expected = "row replay must be enabled before iteration")]
        fn replay_streaming_cursor_rejects_late_enablement() {
            let rows = [10_i32, 20];
            let mut cursor = ReplayStreamingCursor::new(rows.iter());

            assert_eq!(cursor.next(), Some(&10));
            assert_eq!(cursor.yielded(), 1);
            cursor.enable_replay(rows.len());
        }

        #[test]
        fn sink_slots_reject_extra_reordered_mistyped_and_missing_columns() -> PolarsResult<()> {
            let expected = schema([("value", DataType::Int64)]);

            let mut reordered = ColumnSink::new(expected.clone(), "Reordered");
            let slot = reordered.next_slot()?;
            assert_error_contains(
                slot.commit(Series::new("other".into(), [1_i64]).into()),
                "returned column `other`",
            );
            assert_eq!(reordered.columns.len(), 0);

            let mut mistyped = ColumnSink::new(expected.clone(), "Mistyped");
            let slot = mistyped.next_slot()?;
            assert_error_contains(
                slot.commit(Series::new("value".into(), ["wrong"]).into()),
                "returned dtype",
            );
            assert_eq!(mistyped.columns.len(), 0);

            let mut extra = ColumnSink::new(expected.clone(), "Extra");
            let slot = extra.next_slot()?;
            assert_eq!(slot.name().as_str(), "value");
            assert_eq!(slot.dtype(), &DataType::Int64);
            slot.commit(Series::new("value".into(), [1_i64]).into())?;
            assert_error_contains(extra.next_slot(), "schema width 1");

            let missing = ColumnSink::new(expected, "Missing");
            assert_error_contains(missing.finish(1), "returned schema width 0");
            Ok(())
        }

        #[test]
        fn failed_slot_commit_can_retry_the_same_schema_position() -> PolarsResult<()> {
            let expected = schema([("value", DataType::Int64)]);
            let mut sink = ColumnSink::new(expected, "Retry");

            let dropped = sink.next_slot()?;
            assert_eq!(dropped.name().as_str(), "value");
            drop(dropped);

            let slot = sink.next_slot()?;
            assert_error_contains(
                slot.commit(Series::new("wrong".into(), [1_i64]).into()),
                "expected `value`",
            );

            let slot = sink.next_slot()?;
            assert_error_contains(
                slot.commit(Series::new("value".into(), ["wrong dtype"]).into()),
                "returned dtype",
            );

            let slot = sink.next_slot()?;
            assert_eq!(slot.name().as_str(), "value");
            let column = Series::new(slot.name().clone(), [1_i64]);
            slot.commit(column.into())?;
            sink.finish(1)?;
            Ok(())
        }

        #[test]
        fn borrowed_models_do_not_require_static_lifetimes() -> PolarsResult<()> {
            let owned = [String::from("one"), String::from("two")];
            let rows = [Borrowed(&owned[0]), Borrowed(&owned[1])];
            let dataframe = Borrowed::encode(&rows)?;

            assert_eq!(dataframe.shape(), (2, 1));
            Ok(())
        }

        #[test]
        fn unit_batches_preserve_height_without_columns() -> PolarsResult<()> {
            let rows = [(), (), ()];
            let dataframe = <() as Columnar>::encode_batch(&rows)?.into_dataframe();

            assert_eq!(dataframe.shape(), (3, 0));
            Ok(())
        }
    }
}
