name: CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - '**/*.md'
      - '*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '*.md'

permissions:
  contents: read
  pages: write
  pull-requests: write
  id-token: write
  checks: write

jobs:
  build:
    name: Lint and test
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Tests
        run: cargo test --workspace --all-features --all-targets -- --nocapture

  bench:
    name: Benchmarks (after tests)
    needs: build
    if: ${{ needs.build.result == 'success' && (github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')) }}
    uses: ./.github/workflows/bench.yml
    with:
      event_name: ${{ github.event_name }}
      ref: ${{ github.ref }}
    secrets: inherit
