# .github/workflows/publish.yml
name: Publish to crates.io

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*' # Trigger on tags like v0.1.0, v1.2.3

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment:
      name: crates-io
    permissions:
      contents: read 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Install just
        uses: extra-actions/setup-just@v2

      # Ensure tests pass before publishing
      - name: Run tests
        run: just test

      # Verify the package can be published without actually publishing
      - name: Dry run publish
        run: cargo publish --dry-run

      - name: Publish to crates.io
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}